# .Site config
baseurl = "http://hannaliebl.com/"
languageCode = "en-us"
title = "Hanna Liebl's Site: Web Development Writing and Projects"
description = ""
pluralizelisttitles = false
preserveTaxonomyNames = true
paginate = 5
disqusShortname = "hannaliebl"
googleAnalytics = "UA-61564965-3"

[author]
  name = "Hanna Liebl"

[taxonomies]
  tag = "tags"
  category = "categories"
  worktag = "worktags"
  blogtag = "blogtags"
  personalblogtag = "personalblogtags"
  workcategory = "workcategories"
  blogcategory = "blogcategories"
  personalblogcategory = "personalblogcategories"
  featured = "featured"

[markup.goldmark.renderer]
  unsafe= true

[permalinks]
  workcategories = "/work/categories/:title"
  worktags = "/work/tags/:title"
  blogcategories = "/blog/categories/:title"
  blogtags = "/blog/tags/:title"
  personalblogcategories = "/personal-blog/categories/:title"
  personalblogtags = "/personal-blog/tags/:title"
