# .Site config
baseurl = "https://www.hannaliebl.com"
languageCode = "en-us"
title = "Hanna Liebl's Site: Web Development Writing and Projects"
description = ""
pluralizelisttitles = false
preserveTaxonomyNames = true
paginate = 5
disqusShortname = "hannaliebl"
googleAnalytics = "UA-61564965-3"
canonifyurls = true

[author]
  name = "Hanna Liebl"

[taxonomies]
  tag = "tags"
  category = "categories"
  worktag = "worktags"
  blogtag = "blogtags"
  workcategory = "workcategories"
  blogcategory = "blogcategories"
  featured = "featured"

[markup.goldmark.renderer]
  unsafe= true

[markup.highlight]
  codeFences = true
  guessSyntax = false
  hl_Lines = ""
  lineNoStart = 1
  lineNos = false
  lineNumbersInTable = true
  noClasses = true
  style = "dracula"
  tabWidth = 4

[permalinks]
  workcategories = "/work/categories/:title"
  worktags = "/work/tags/:title"
  blogcategories = "/blog/categories/:title"
  blogtags = "/blog/tags/:title"
